// packages/angular/examples/provider-panel.component.ts
import { Component, Input, OnDestroy, inject } from '@angular/core';
import { ProviderRoutingService } from '@weaveai/angular';
import type { UIAwareProviderRouter } from '@weaveai/core';

@Component({
  selector: 'app-provider-panel-example',
  template: `
    <section>
      <h2>Routing Status</h2>
      <article *ngFor="let provider of routingState.providers">
        <h3>{{ provider.name }}</h3>
        <p>Status: {{ provider.healthy ? 'Healthy' : 'Offline' }}</p>
        <p>Latency: {{ provider.latency | number: '1.0-0' }} ms</p>
        <p>Success: {{ provider.successRate | number: '1.1-1' }}%</p>
        <button
          (click)="selectProvider(provider.name)"
          [disabled]="!provider.healthy"
        >
          Route here
        </button>
      </article>

      <h3>Recent events</h3>
      <ul>
        <li *ngFor="let event of routingState.events">
          <strong>{{ event.type }}</strong>:
          <span *ngIf="event.from">
            {{ event.from }} → {{ event.to }}
          </span>
          <span *ngIf="!event.from">{{ event.to }}</span>
          <small>{{ event.timestamp.toLocaleTimeString() }}</small>
        </li>
      </ul>
    </section>
  `,
})
export class ProviderPanelComponent implements OnDestroy {
  private readonly routing = inject(ProviderRoutingService);
  routingState = this.routing.getState();

  @Input()
  set router(router: UIAwareProviderRouter | null) {
    if (router) {
      this.routing.initialise(router, { autoRefresh: true, refreshInterval: 5000 });
      this.routingState = this.routing.getState();
    }
  }

  selectProvider(provider: string): void {
    this.routing.selectProvider(provider);
    this.routingState = this.routing.getState();
  }

  ngOnDestroy(): void {
    this.routing.dispose();
  }
}

// packages/vue/examples/ProviderPanel.vue
<script setup lang="ts">
import { useProviderRouting } from '@weaveai/vue';
import type { UIAwareProviderRouter } from '@weaveai/core';

const props = defineProps<{
  router: UIAwareProviderRouter;
}>();

const routing = useProviderRouting({
  router: props.router,
  autoRefresh: true,
  refreshInterval: 5000,
});
</script>

<template>
  <section class="panel">
    <h2>Provider Routing</h2>
    <div class="providers">
      <article
        v-for="provider in routing.providers"
        :key="provider.name"
        :class="{ active: provider.name === routing.currentProvider }"
      >
        <h3>{{ provider.name }}</h3>
        <p>Status: {{ provider.healthy ? 'Healthy' : 'Offline' }}</p>
        <p>Success: {{ provider.successRate.toFixed(1) }}%</p>
        <p>Latency: {{ provider.latency.toFixed(0) }}ms</p>
        <button
          :disabled="!provider.healthy"
          @click="routing.selectProvider(provider.name)"
        >
          Route here
        </button>
      </article>
    </div>

    <ol class="events">
      <li v-for="(event, index) in routing.events" :key="index">
        <strong>{{ event.type }}</strong>
        <span v-if="event.from">: {{ event.from }} → {{ event.to }}</span>
        <span v-else>: {{ event.to }}</span>
        <small>{{ event.timestamp.toLocaleTimeString() }}</small>
      </li>
    </ol>
  </section>
</template>
