// packages/vue/examples/ConciergeChat.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useAIChat } from '@weaveai/vue';

const input = ref('');
const chat = useAIChat({
  systemPrompt: 'You are a charming concierge for a boutique hotel.',
  streaming: { enabled: true, renderer: 'markdown' },
  persistence: { localStorage: 'concierge-chat', autoSave: true },
});

const send = async () => {
  if (!input.value.trim()) {
    return;
  }

  await chat.sendMessage(input.value);
  input.value = '';
};
</script>

<template>
  <section class="chat-card">
    <h2>Concierge</h2>
    <ul>
      <li v-for="(message, index) in chat.messages" :key="index">
        <strong>{{ message.role }}:</strong>
        <span>{{ message.content }}</span>
      </li>
    </ul>

    <form @submit.prevent="send">
      <input v-model="input" placeholder="Ask the concierge…" />
      <button :disabled="chat.isLoading">Send</button>
    </form>
  </section>
</template>

// packages/react-native/examples/ConciergeChat.tsx
import { useState } from 'react';
import { View, Text, TextInput, Button, FlatList } from 'react-native';
import { useAIChat } from '@weaveai/react-native';
import type { Weave } from '@weaveai/core';

export function ConciergeChat({ weave }: { weave: Weave }) {
  const chat = useAIChat(weave, {
    systemPrompt: 'You are a warm concierge for a boutique hotel.',
    streaming: { enabled: true, renderer: 'markdown' },
    persistence: { localStorage: 'concierge-chat', autoSave: true },
  });
  const [input, setInput] = useState('');

  const send = async () => {
    if (!input.trim()) return;
    await chat.sendMessage(input);
    setInput('');
  };

  return (
    <View style={{ flex: 1, padding: 16, gap: 12 }}>
      <FlatList
        data={chat.messages}
        keyExtractor={(_, index) => index.toString()}
        renderItem={({ item }) => (
          <View style={{ marginBottom: 8 }}>
            <Text style={{ fontWeight: '600' }}>{item.role}</Text>
            <Text>{item.content}</Text>
          </View>
        )}
      />

      <TextInput
        value={input}
        onChangeText={setInput}
        placeholder="Ask the concierge…"
        style={{
          borderWidth: 1,
          borderColor: '#d1d5db',
          borderRadius: 12,
          padding: 12,
        }}
      />

      <Button title="Send" onPress={send} disabled={chat.isLoading} />
    </View>
  );
}
